refine infrastructure

diff --git a/rc/bashrc b/rc/bashrc
--- a/rc/bashrc
+++ b/rc/bashrc
@@ -36,7 +36,8 @@ fi
 # source shell-utils
 su::initialize() {
 	local mod f
-	for mod in lib core opt ext custom; do
+	PATH="$PATH:/${SHELL_UTILS_HOME}/bin"
+	for mod in core opt ext custom; do
 		mod="${SHELL_UTILS_HOME}/${mod}"
 		if [ -d "${mod}" ]; then
 			for f in "$mod"/*.sh; do
@@ -52,85 +53,10 @@ su::initialize() {
 				fi
 			done
 		else
-			echo "module not found: [$i]" >&2
+			echo "module not found: [$mod]" >&2
 			return 1
 		fi
 	done
 }
 su::initialize
 unset -f SU::initialize
-
-log() {
-	local OPTIND=1
-	local opt
-	while getopts "h:v" opt; do
-		case "$opt" in
-			h)
-				cat << EOF
-Usage: ${FUNCNAME[0]} [option] level message ...
-  options:
-	-h	show this message and exit
-	-v  verbose output
-  level:
-  	debug
-	info
-	warning
-	error
-EOF
-				;;
-			v)
-				;;
-		esac
-	done
-	shift $((OPTIND-1))
-	if [ $# -lt 2 ]; then
-		log 'error' "2 or more arguments expected, but $# found"
-		return 1
-	fi
-	case "$level" in
-		debug)
-			if [ $VERBOSE -le 0 ]; then
-				return
-			fi
-			;;
-		info)
-			if [ $VERBOSE -le 1 ]; then
-				return
-			fi
-			;;
-		warning)
-			if [ $VERBOSE -le 2 ]; then
-				return
-			fi
-			;;
-		error)
-			;;
-	esac
-	echo "[${FUNCNAME[0]} ${level}] $*"
-}
-
-use() {
-	local OPTIND=1
-	local opt
-	while getopts "h:v" opt; do
-		case "$opt" in
-			h)
-				;;
-			v)
-				;;
-		esac
-	done
-	shift $((OPTIND-1))
-	if [ $# -eq 0 ]; then
-		log 'error'
-	fi
-	local mod
-	for mod in "$@"; do
-		echo "[$mod]"
-	done
-	return
-}
-
-use core \
-	ext	\
-	lib
